name: Deploy Cambodia Law Library Web App

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Static Web Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'src'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
